(DEFINE (sum-up-numbers-general L)
        (cond ((null? L) 0)
              ((list? (car L))(+(car (car L))(sum-up-numbers-general(cdr L))))
              ((number? (car L))(+(car L)(sum-up-numbers-general(cdr L))))
              )
        )